name: DPclust-nf
channels:
  - conda-forge
  - bioconda
dependencies:
  - r-optparse
  - bioconductor-variantannotation
  - bioconductor-genomicranges
  - bioconductor-rsamtools
  - r-ggplot2
  - bioconductor-iranges
  - bioconductor-s4vectors
  - r-reshape2
  - r-kernsmooth
  - r-ks
  - r-lattice
  - r-gridExtra
  - r-devtools
  - r-tidyverse
